## NumPy 

In [1]:
import numpy as np

In [2]:
# Numpy provides efficient storage
# It is fast
# It uses less memory to store data.

In [8]:
myarr= np.array([[1,2,3,4,5]])

In [9]:
myarr

array([[1, 2, 3, 4, 5]])

In [12]:
myarr[0,1]

np.int64(2)

In [13]:
myarr.shape

(1, 5)

In [14]:
myarr.dtype

dtype('int64')

## 5 General Mechanism for creating nunpy arrays

In [15]:
### 1. Conversion from  other python structures like list, tuple

In [17]:
myarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [18]:
myarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
myarray.size

9

In [20]:
myarray.shape

(3, 3)

In [22]:
myarray.dtype

dtype('int64')

In [23]:
## Intrinsic Numpy array creation

In [24]:
zeros = np.zeros((2,5))

In [25]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [26]:
zeros.shape

(2, 5)

In [27]:
zeros.dtype

dtype('float64')

In [28]:
rng = np.arange(15)

In [29]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
rangg = np.arange(4,15)

In [35]:
rangg

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [36]:
lspace = np.linspace(2,10,5)

In [37]:
lspace

array([ 2.,  4.,  6.,  8., 10.])

In [39]:
lspace = np.linspace(2,10,10)
lspace

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [40]:
lspace = np.linspace(2,40,10)
lspace

array([ 2.        ,  6.22222222, 10.44444444, 14.66666667, 18.88888889,
       23.11111111, 27.33333333, 31.55555556, 35.77777778, 40.        ])

In [41]:
idd =  np.identity(45)

In [42]:
idd

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [43]:
Id = np.identity(4)
Id

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [44]:
Id.shape

(4, 4)

In [45]:
arr= np.arange(99)

In [46]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [47]:
arr.reshape(9,11)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
       [22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43],
       [44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54],
       [55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76],
       [77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87],
       [88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98]])

In [48]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [49]:
arr.shape

(99,)

In [50]:
arr = arr.reshape(3,33)

In [51]:
arr.shape

(3, 33)

In [53]:
arr= arr.ravel()

In [54]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [55]:
arr.shape

(99,)

In [56]:
arr= np.array([[2,3,4],[5,6,7],[3,8,9]])

In [57]:
arr

array([[2, 3, 4],
       [5, 6, 7],
       [3, 8, 9]])

In [58]:
arr.sum(axis=0)  # will add vertically

array([10, 17, 20])

In [59]:
arr.sum(axis=1)  # will add horizontally

array([ 9, 18, 20])

In [60]:
arr.ndim

2

In [61]:
arr.ndim

2

In [62]:
arr.T

array([[2, 5, 3],
       [3, 6, 8],
       [4, 7, 9]])

In [63]:
arr

array([[2, 3, 4],
       [5, 6, 7],
       [3, 8, 9]])

In [64]:
for i in arr.flat:
    print(i)

2
3
4
5
6
7
3
8
9


In [66]:
arr.flat

In [67]:
arr.size

9

In [68]:
arr

array([[2, 3, 4],
       [5, 6, 7],
       [3, 8, 9]])

In [70]:
arr.argmin()   # tell the position of min value in array

np.int64(0)

In [71]:
arr.argmax()   # position of max value inside the list

np.int64(8)

In [72]:
arr.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [73]:
[4,5,7]+[1,5,3]

[4, 5, 7, 1, 5, 3]

In [74]:
## addition not happeningh in list, but it happens in numpy

In [75]:
arr

array([[2, 3, 4],
       [5, 6, 7],
       [3, 8, 9]])

In [77]:
arr1 = np.array([[1,1,1],[4,2,3],[3,5,2]])

In [78]:
arr1

array([[1, 1, 1],
       [4, 2, 3],
       [3, 5, 2]])

In [79]:
arr2 = arr+ arr1
arr2

array([[ 3,  4,  5],
       [ 9,  8, 10],
       [ 6, 13, 11]])

In [80]:
arr3 = arr-arr1
arr3

array([[1, 2, 3],
       [1, 4, 4],
       [0, 3, 7]])

In [81]:
arr4= arr*arr1
arr4

array([[ 2,  3,  4],
       [20, 12, 21],
       [ 9, 40, 18]])

In [82]:
arr

array([[2, 3, 4],
       [5, 6, 7],
       [3, 8, 9]])

In [83]:
arr1

array([[1, 1, 1],
       [4, 2, 3],
       [3, 5, 2]])

In [84]:
## multiplication is happening with corresponding elements

In [85]:
arr5 = arr/arr1
arr5

array([[2.        , 3.        , 4.        ],
       [1.25      , 3.        , 2.33333333],
       [1.        , 1.6       , 4.5       ]])

In [86]:
## addition, subtraction, divison and multiplication is happening with corresponding elements

In [87]:
np.sqrt(arr)

array([[1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131],
       [1.73205081, 2.82842712, 3.        ]])

In [89]:
arr.sum()   ## sum of all the elements

np.int64(47)

In [90]:
arr.max()

np.int64(9)

In [91]:
arr.min()

np.int64(2)

In [92]:
np.count_nonzero(arr)

9

In [93]:
## For more simply google search, numpy array attributes and methods.

In [94]:
arr

array([[2, 3, 4],
       [5, 6, 7],
       [3, 8, 9]])

In [97]:
arr[:,1]   # 1st column

array([3, 6, 8])

In [98]:
arr[:,2]

array([4, 7, 9])

In [100]:
arr[0,:]   # first row

array([2, 3, 4])

In [101]:
arr[1,2]    # 2nd row and 3rd column element

np.int64(7)

In [102]:
## row and column index starts from 0,1,2,3....

In [103]:
arr>5

array([[False, False, False],
       [False,  True,  True],
       [False,  True,  True]])

In [104]:
arr>2

array([[False,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [105]:
arr < 1

array([[False, False, False],
       [False, False, False],
       [False, False, False]])

In [106]:
arr.shape

(3, 3)

In [109]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [110]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])