## Numpy

In [1]:
# Numpy stands for NUmerical Python.
# Operations using Numpy:-
# 1. Mathematical  and logical operations on array.
# 2. Operations related to linear algebra.
# 3. Random number generations.
# 4. Fourier  transform etc.

In [2]:
# Array

In [3]:
# Arrays are similar to list in Python except that Arrays have same data types.

In [4]:
import numpy as np

In [5]:
arr = np.array([1,2,3,4,5], float)

In [6]:
arr

array([1., 2., 3., 4., 5.])

In [7]:
type(arr)

numpy.ndarray

In [8]:
# creating a 2D array

In [9]:
arr1 = np.array([[2,3,5],[5,3,7]])

In [10]:
arr1

array([[2, 3, 5],
       [5, 3, 7]])

In [11]:
arr1[0]

array([2, 3, 5])

In [13]:
arr1[1]

array([5, 3, 7])

In [15]:
arr1[0][2] #firt is for row and second is for column

np.int64(5)

In [16]:
arr1[:,:]

array([[2, 3, 5],
       [5, 3, 7]])

In [17]:
arr1[:,1]

array([3, 3])

In [18]:
arr1

array([[2, 3, 5],
       [5, 3, 7]])

In [20]:
arr1[1,:]

array([5, 3, 7])

In [21]:
# Identity matrix

In [22]:
arr2 = np.eye(5)

In [23]:
arr2

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [26]:
np.random.random([2,3])

array([[0.40869442, 0.23227914, 0.14585745],
       [0.04372504, 0.95239846, 0.06891884]])

In [27]:
np.random.rand(2,3)

array([[0.07150129, 0.22470125, 0.58918845],
       [0.00104969, 0.19401081, 0.02662306]])

In [30]:
np.random.randint(1,100)

17

In [33]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [34]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.full([4,4],6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [36]:
# will make a 4x4 matrix with each of its elements as 6

In [38]:
arr3=np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [39]:
arr3

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [40]:
arr3.shape

(2, 5)

In [41]:
arr3.dtype

dtype('int64')

In [42]:
arr3.reshape(5,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [43]:
arr3.T

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])

In [45]:
arr3.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Numpy Concatenate function

In [50]:
arr4 = np.array([[1,2],[3,4]],float)
arr5 = np.array([[4,2],[5,6]],float)
print(np.concatenate([arr4,arr5]))

[[1. 2.]
 [3. 4.]
 [4. 2.]
 [5. 6.]]


In [51]:
print(np.concatenate([arr4,arr5],axis =1))

[[1. 2. 4. 2.]
 [3. 4. 5. 6.]]


In [52]:
print(np.concatenate([arr4,arr5],axis =0))

[[1. 2.]
 [3. 4.]
 [4. 2.]
 [5. 6.]]


### Array Mathematics

In [53]:
arr4

array([[1., 2.],
       [3., 4.]])

In [54]:
arr5

array([[4., 2.],
       [5., 6.]])

In [55]:
arr5/arr4

array([[4.        , 1.        ],
       [1.66666667, 1.5       ]])

In [56]:
arr4*arr5    # multiply correspomding elements only.

array([[ 4.,  4.],
       [15., 24.]])

In [57]:
arr5-arr4

array([[3., 0.],
       [2., 2.]])

In [58]:
arr4+arr5

array([[ 5.,  4.],
       [ 8., 10.]])

In [59]:
arr4

array([[1., 2.],
       [3., 4.]])

In [60]:
arr4+5

array([[6., 7.],
       [8., 9.]])

In [61]:
arr4+[1,2]

array([[2., 4.],
       [4., 6.]])

In [62]:
arr6=np.array([[3,2],[7,8],[5,9]])   # is 3 x 2 matrix

In [63]:
arr6

array([[3, 2],
       [7, 8],
       [5, 9]])

In [64]:
arr5

array([[4., 2.],
       [5., 6.]])

In [65]:
arr5*arr6

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [66]:
arr6*arr5

ValueError: operands could not be broadcast together with shapes (3,2) (2,2) 

In [67]:
# This is not the matrix multipliction as we do in mathematics

### Array iteration

In [68]:
arr6

array([[3, 2],
       [7, 8],
       [5, 9]])

In [69]:
for x in arr6:
    print(x)

[3 2]
[7 8]
[5 9]


In [70]:
for x,y in arr6:
    print(x+y)

5
15
14


In [71]:
for x,y in arr6:
    print(x,y)

3 2
7 8
5 9


In [72]:
arr6

array([[3, 2],
       [7, 8],
       [5, 9]])

In [73]:
arr6.prod()

np.int64(15120)

In [75]:
arr6.prod(axis=0)

array([105, 144])

In [76]:
arr6.prod(axis=1)

array([ 6, 56, 45])

In [77]:
arr6.sum()

np.int64(34)

In [78]:
print(arr6.sum(axis=0))
print(arr6.sum(axis=1))

[15 19]
[ 5 15 14]


In [79]:
arr6

array([[3, 2],
       [7, 8],
       [5, 9]])

In [80]:
arr6.mean()

np.float64(5.666666666666667)

In [81]:
print(arr6.mean(axis=0))
print(arr6.mean(axis=1))

[5.         6.33333333]
[2.5 7.5 7. ]


In [82]:
## Variance

In [83]:
arr6.var()

np.float64(6.555555555555556)

In [84]:
print(arr6.var(axis=0))
print(arr6.var(axis=1))

[2.66666667 9.55555556]
[0.25 0.25 4.  ]


In [85]:
arr6.std()

np.float64(2.560381915956203)

In [86]:
print(arr6.std(axis=0))
print(arr6.std(axis=1))

[1.63299316 3.09120617]
[0.5 0.5 2. ]


In [87]:
arr6.min()

np.int64(2)

In [89]:
print(arr6.min(axis=0))
print(arr6.min(axis=1))

[3 2]
[2 7 5]


In [90]:
arr6

array([[3, 2],
       [7, 8],
       [5, 9]])

In [91]:
arr6.max()

np.int64(9)

In [92]:
print(arr6.max(axis=0))
print(arr6.max(axis=1))

[7 9]
[3 8 9]


In [93]:
arr7 = np.array([[5,7,4],[8,2,1]])

In [94]:
arr7

array([[5, 7, 4],
       [8, 2, 1]])

In [96]:
print(arr7.argmin())

5


In [97]:
print(arr7.argmin(axis=0))

[0 1 1]


In [98]:
print(arr7.argmin(axis=1))

[2 2]


In [99]:
print(arr7.argmax())

3


In [100]:
print(arr7.argmax(axis=0))

[1 0 0]


In [101]:
print(arr7.argmax(axis=1))

[1 0]


In [102]:
## Last slide left to cover 

In [5]:
arr8 = np.array([[5,7,4],[8,2,1]])

In [6]:
arr8

array([[5, 7, 4],
       [8, 2, 1]])

In [12]:
arr8.sort()
print(arr8)

[[1 2 7]
 [4 5 8]]


In [13]:
arr8.sort(axis=0)
print(arr8)

[[1 2 7]
 [4 5 8]]


In [14]:
arr8.sort(axis=1)
print(arr8)

[[1 2 7]
 [4 5 8]]


In [15]:
arr8.diagonal()

array([1, 5])

In [16]:
arr9 = np.array([[4,5,6],[4,0,2],[7,8,3]])

In [17]:
arr9.diagonal()

array([4, 0, 3])

In [19]:
ar1= np.array([[4,5],[7,2]])
ar2= np.array([[2,5],[1,1]])

In [20]:
print(ar1)
print(ar2)

[[4 5]
 [7 2]]
[[2 5]
 [1 1]]


In [21]:
np.dot(ar1,ar2)

array([[13, 25],
       [16, 37]])

In [22]:
np.dot(ar2,ar1)

array([[43, 20],
       [11,  7]])

In [24]:
ar3=np.array([[1,2,3],[4,5,6]])

In [25]:
np.dot(ar1,ar3)

array([[24, 33, 42],
       [15, 24, 33]])

In [27]:
np.dot(ar3,ar1)  # mathematicalyy not possible

ValueError: shapes (2,3) and (2,2) not aligned: 3 (dim 1) != 2 (dim 0)

In [28]:
ar1>ar2

array([[ True, False],
       [ True,  True]])

In [29]:
ar1>5

array([[False, False],
       [ True, False]])

In [30]:
ar2<100

array([[ True,  True],
       [ True,  True]])

In [31]:
a = np.array([1,2,3],float)
b = np.array([4,2,6],float)

In [32]:
np.outer(b,a)

array([[ 4.,  8., 12.],
       [ 2.,  4.,  6.],
       [ 6., 12., 18.]])

In [33]:
np.outer(a,b)

array([[ 4.,  2.,  6.],
       [ 8.,  4., 12.],
       [12.,  6., 18.]])

In [36]:
print(np.inner(a,b))

26.0


In [37]:
print(np.inner(b,a))

26.0
